OK

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,134 +43,134 @@ commands:
             npm install
             npm run migration:revert
 jobs:
-  # build-frontend:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     - checkout
-  #     - restore_cache:
-  #         keys: [frontend-build]
-  #     - run:
-  #         name: Build front-end
-  #         command: |
-  #           # Your code here
-  #           cd frontend
-  #           npm install
-  #           npm run build
-  #           # exit 1
-  #     - save_cache:
-  #         paths: [frontend/node_modules]
-  #         key: frontend-build
+  build-frontend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Build front-end
+          command: |
+            # Your code here
+            cd frontend
+            npm install
+            npm run build
+            # exit 1
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
 
-  # build-backend:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     - checkout
-  #     - restore_cache:
-  #         keys: [backend-build]
-  #     - run:
-  #         name: Back-end build
-  #         command: |
-  #            # Your code here
-  #            cd backend
-  #            npm install
-  #            npm run build
-  #            # exit 1
-  #     - save_cache:
-  #         paths: [backend/node_modules]
-  #         key: backend-build
-  # test-frontend:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     # Checkout code from git
-  #     - checkout
-  #     # Restore from cache
-  #     - restore_cache:
-  #         keys: [frontend-build]
-  #     # Your job code here
-  #     - run:
-  #         name: Front-end build
-  #         command: |
-  #            # Your code here
-  #            cd frontend
-  #            npm install
-  #            npm run test
-  #            # exit 1
-  #     # - save_cache:
-  #     #     paths: [frontend/node_modules]
-  #     #     key: frontend-test
-  # test-backend:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     # Checkout code from git
-  #     - checkout
-  #     # Restore from cache
-  #     - restore_cache:
-  #         keys: [backend-build]
-  #     # Your job code here
-  #     - run:
-  #         name: Back-end build
-  #         command: |
-  #            # Your code here
-  #            cd backend
-  #            npm install
-  #            npm run test
-  #            # exit 1
-  #     # - save_cache:
-  #     #     paths: [backend/node_modules]
-  #     #     key: backend-test
-  # scan-frontend:
-  #   docker:
-  #     # Docker image here
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     # Checkout code from git
-  #     - checkout
-  #     # Restore from cache
-  #     - restore_cache:
-  #         keys: [frontend-build]
-  #     # Your job code here
-  #     - run:
-  #         name: Front-end build
-  #         command: |
-  #            # Your code here
-  #            cd frontend
-  #            npm install
-  #            npm audit fix --force
-  #            npm audit fix --force
-  #            npm audit --audit-level=critical
-  #            # exit 1
-  #     # - save_cache:
-  #     #     paths: [frontend/node_modules]
-  #     #     key: frontend-scan
+  build-backend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Back-end build
+          command: |
+             # Your code here
+             cd backend
+             npm install
+             npm run build
+             # exit 1
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
+  test-frontend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [frontend-build]
+      # Your job code here
+      - run:
+          name: Front-end build
+          command: |
+             # Your code here
+             cd frontend
+             npm install
+             npm run test
+             # exit 1
+      # - save_cache:
+      #     paths: [frontend/node_modules]
+      #     key: frontend-test
+  test-backend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [backend-build]
+      # Your job code here
+      - run:
+          name: Back-end build
+          command: |
+             # Your code here
+             cd backend
+             npm install
+             npm run test
+             # exit 1
+      # - save_cache:
+      #     paths: [backend/node_modules]
+      #     key: backend-test
+  scan-frontend:
+    docker:
+      # Docker image here
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [frontend-build]
+      # Your job code here
+      - run:
+          name: Front-end build
+          command: |
+             # Your code here
+             cd frontend
+             npm install
+             npm audit fix --force
+             npm audit fix --force
+             npm audit --audit-level=critical
+             # exit 1
+      # - save_cache:
+      #     paths: [frontend/node_modules]
+      #     key: frontend-scan
 
-  # scan-backend:
-  #   docker:
-  #     # Docker image here
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     # Checkout code from git
-  #     - checkout
-  #     # Restore from cache
-  #     - restore_cache:
-  #         keys: [backend-build]
-  #     # Your job code here
-  #     - run:
-  #         name: Back-end build
-  #         command: |
-  #            # Your code here
-  #            cd backend
-  #            npm install
-  #            npm audit fix --force
-  #            npm audit fix --force
-  #            npm audit --audit-level=critical
-  #            # exit 1
-  #     # - save_cache:
-  #     #     paths: [backend/node_modules]
-  #     #     key: backend-scan
+  scan-backend:
+    docker:
+      # Docker image here
+      - image: circleci/node:13.8.0
+    steps:
+      # Checkout code from git
+      - checkout
+      # Restore from cache
+      - restore_cache:
+          keys: [backend-build]
+      # Your job code here
+      - run:
+          name: Back-end build
+          command: |
+             # Your code here
+             cd backend
+             npm install
+             npm audit fix --force
+             npm audit fix --force
+             npm audit --audit-level=critical
+             # exit 1
+      # - save_cache:
+      #     paths: [backend/node_modules]
+      #     key: backend-scan
   # deploy-infrastructure:
   #   docker:
   #     # Docker image here that supports AWS CLI
@@ -284,86 +284,86 @@ jobs:
   #     # Here's where you will add some code to rollback on failure
   #     - destroy-environment
   #     - revert-migrations
-  deploy-frontend:
-    docker:
-      # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-            yum install -y curl tar gzip sudo
-            # Install Nodejs
-            curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
-            yum install -y nodejs npm
-      # attach workspace
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            export BACKEND_IP=${aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text}
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: Deploy frontend objects
-          command: |
-            # your code here
-            cd frontend
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      # Here's where you will add some code to rollback on failure      
-      - destroy-environment
-      - revert-migrations
+  # deploy-frontend:
+  #   docker:
+  #     # Docker image here that supports AWS CLI
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           # your code here
+  #           yum install -y curl npm tar gzip sudo
+  #           # Install Nodejs
+  #           curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
+  #           yum install -y nodejs
+  #     # attach workspace
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Get backend url
+  #         command: |
+  #           # your code here
+  #           export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "API_URL = ${API_URL}"
+  #           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+  #           cat frontend/.env
+  #     - run:
+  #         name: Deploy frontend objects
+  #         command: |
+  #           # your code here
+  #           cd frontend
+  #           npm run build
+  #           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+  #           aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+  #     # Here's where you will add some code to rollback on failure      
+  #     - destroy-environment
+  #     - revert-migrations
 
-  deploy-backend:
-    docker:
-      # Docker image here that supports Ansible
-      - image: python:3.11-rc-alpine
-    steps:
-      # Checkout code from git
-      - checkout
-      # Add ssh keys with fingerprint
-      - add_ssh_keys:
-          fingerprints:
-            - "05:0b:92:eb:60:7b:e0:e8:c9:0a:cd:6c:9c:ee:ff:07"
-      # attach workspace
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-            apk add --update ansible npm curl tar gzip sudo
-            pip install awscli
-            #apk install -y curl tar gzip sudo
-            # Install Nodejs
-            curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
-            #yum install -y nodejs
-            apk add --update nodejs npm
-      - run:
-          name: Deploy backend
-          command: |
-            # your code here
-            cd backend
-            npm i
-            npm run build
-            cd ..
-            tar -C backend -czvf artifact.tar.gz .
-            cd .circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
-      # Here's where you will add some code to rollback on failure  
-      - destroy-environment
-      - revert-migrations
+  # deploy-backend:
+  #   docker:
+  #     # Docker image here that supports Ansible
+  #     - image: python:3.11-rc-alpine
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     # Add ssh keys with fingerprint
+  #     - add_ssh_keys:
+  #         fingerprints:
+  #           - "05:0b:92:eb:60:7b:e0:e8:c9:0a:cd:6c:9c:ee:ff:07"
+  #     # attach workspace
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           # your code here
+  #           apk add --update ansible npm curl tar gzip sudo bash
+  #           pip install awscli
+  #           #apk install -y curl tar gzip sudo
+  #           # Install Nodejs
+  #           curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
+  #           #yum install -y nodejs
+  #           apk add --update nodejs npm
+  #     - run:
+  #         name: Deploy backend
+  #         command: |
+  #           # your code here
+  #           cd backend
+  #           npm i
+  #           npm run build
+  #           cd ..
+  #           tar -C backend -czvf artifact.tar.gz .
+  #           cd .circleci/ansible
+  #           echo "Contents  of the inventory.txt file is -------"
+  #           cat inventory.txt
+  #           ansible-playbook -i inventory.txt deploy-backend.yml
+  #     # Here's where you will add some code to rollback on failure  
+  #     - destroy-environment
+  #     - revert-migrations
   # smoke_test:
   #   docker:
   #     - image: alpine:latest
@@ -376,7 +376,7 @@ jobs:
   #     - run:
   #         name: Get backend url
   #         command: |
-  #           export BACKEND_IP=${aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text}
+  #           export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
   #           export URL="http://${BACKEND_IP}:3030"
   #           echo ${URL}
   #     - run:
@@ -459,16 +459,16 @@ jobs:
 workflows:
   default:
     jobs:
-      # - build-frontend
-      # - build-backend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - test-backend:
-      #     requires: [build-backend]
-      # - scan-backend:
-      #     requires: [build-backend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
+      - build-frontend
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
       # - deploy-infrastructure
       #     # requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       #     # filters:
@@ -478,7 +478,7 @@ workflows:
       #     requires: [deploy-infrastructure]
       # - run-migrations:
       #     requires: [configure-infrastructure]
-      - deploy-frontend
-        # requires: [run-migrations]
-      - deploy-backend
-        # requires: [run-migrations]
+      # - deploy-frontend
+      #   # requires: [run-migrations]
+      # - deploy-backend
+      #   # requires: [run-migrations]
